client_id = "#{Project.Terraform.Variables[client_id]}"
client_secret = "#{Project.Terraform.Variables[client_secret]}"
cluster_name = "#{Project.Terraform.Variables[cluster_name]}"
location = "#{Project.Terraform.Variables[location]}"
kubernetes_version = "#{Project.Terraform.Variables[kubernetes_version]}"
resource_group_name = "#{Project.Terraform.Variables[resource_group_name]}"
subscription_id = "#{Project.Terraform.Variables[subscription_id]}"
tenant_id = "#{Project.Terraform.Variables[tenant_id]}"
